language: ruby

sudo: false
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.1
  - 2.2

script: bundle exec rspec

gemfile:
  - spec/gemfiles/Gemfile-rspec-3.3.x
  - spec/gemfiles/Gemfile-rspec-3.4.x

